using IplStore.Domain.Catalog;
using IplStore.Infrastructure.Persistence.ReadModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IplStore.Infrastructure.Persistence.Configurations;

// Column names come from UseSnakeCaseNamingConvention() (StockQuantity -> stock_quantity).
// Only table names, types and relationships are configured explicitly here.
// Keys are generated by the application => ValueGeneratedNever (also stops EF from treating
// a new child with a pre-set key as "existing" and issuing an UPDATE instead of an INSERT).

internal sealed class FranchiseConfiguration : IEntityTypeConfiguration<Franchise>
{
    public void Configure(EntityTypeBuilder<Franchise> builder)
    {
        builder.ToTable("franchises");
        builder.HasKey(f => f.Id);
        builder.Property(f => f.Id).ValueGeneratedNever();
        builder.Property(f => f.Code).HasMaxLength(8);
        builder.Property(f => f.Name).HasMaxLength(100);
        builder.Property(f => f.City).HasMaxLength(60);
        builder.Property(f => f.PrimaryColor).HasMaxLength(7).IsFixedLength();
    }
}

internal sealed class ProductCategoryConfiguration : IEntityTypeConfiguration<ProductCategory>
{
    public void Configure(EntityTypeBuilder<ProductCategory> builder)
    {
        builder.ToTable("product_categories");
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).ValueGeneratedNever();
        builder.Property(c => c.Code).HasMaxLength(40);
        builder.Property(c => c.Name).HasMaxLength(80);
    }
}

internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("products");
        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id).ValueGeneratedNever();
        builder.Property(p => p.Sku).HasMaxLength(40);
        builder.Property(p => p.Name).HasMaxLength(200);
        builder.Property(p => p.Price).HasPrecision(12, 2);
        builder.Property(p => p.Currency).HasMaxLength(3).IsFixedLength();
        builder.Property(p => p.ImageUrl).HasMaxLength(500);

        // PostgreSQL system column xmin changes on every row update -> free optimistic
        // concurrency token without an extra column.
        builder.Property(p => p.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        builder.HasOne(p => p.Franchise).WithMany().HasForeignKey(p => p.FranchiseId);
        builder.HasOne(p => p.Category).WithMany().HasForeignKey(p => p.CategoryId);
    }
}

internal sealed class CatalogItemConfiguration : IEntityTypeConfiguration<CatalogItem>
{
    public void Configure(EntityTypeBuilder<CatalogItem> builder)
    {
        builder.ToTable("product_catalog");
        builder.HasKey(c => c.ProductId);
        builder.Property(c => c.Price).HasPrecision(12, 2);
        builder.Property(c => c.Currency).HasMaxLength(3).IsFixedLength();
        builder.Property(c => c.FranchiseColor).HasMaxLength(7).IsFixedLength();
        builder.Property(c => c.Attributes).HasColumnType("jsonb");
        builder.Property(c => c.SearchText).ValueGeneratedOnAddOrUpdate();
    }
}
