using IplStore.Infrastructure.Persistence.ReadModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IplStore.Infrastructure.Persistence.Configurations;

// Column names come from UseSnakeCaseNamingConvention() (StockQuantity -> stock_quantity).
// Only table names, types and relationships are configured explicitly here.
// Keys are generated by the application => ValueGeneratedNever (also stops EF from treating
// a new child with a pre-set key as "existing" and issuing an UPDATE instead of an INSERT).

internal sealed class CatalogItemConfiguration : IEntityTypeConfiguration<CatalogItem>
{
    public void Configure(EntityTypeBuilder<CatalogItem> builder)
    {
        builder.ToTable("product_catalog");
        builder.HasKey(c => c.ProductId);
        builder.Property(c => c.Price).HasPrecision(12, 2);
        builder.Property(c => c.Currency).HasMaxLength(3).IsFixedLength();
        builder.Property(c => c.FranchiseColor).HasMaxLength(7).IsFixedLength();
        builder.Property(c => c.Attributes).HasColumnType("jsonb");
        builder.Property(c => c.SearchText).ValueGeneratedOnAddOrUpdate();
    }
}
