using IplStore.Domain.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IplStore.Infrastructure.Persistence.Configurations;

// Column names come from UseSnakeCaseNamingConvention() (StockQuantity -> stock_quantity).
// Only table names, types and relationships are configured explicitly here.
// Keys are generated by the application => ValueGeneratedNever (also stops EF from treating
// a new child with a pre-set key as "existing" and issuing an UPDATE instead of an INSERT).

internal sealed class FranchiseConfiguration : IEntityTypeConfiguration<Franchise>
{
    public void Configure(EntityTypeBuilder<Franchise> builder)
    {
        builder.ToTable("franchises");
        builder.HasKey(f => f.Id);
        builder.Property(f => f.Id).ValueGeneratedNever();
        builder.Property(f => f.Code).HasMaxLength(8);
        builder.Property(f => f.Name).HasMaxLength(100);
        builder.Property(f => f.City).HasMaxLength(60);
        builder.Property(f => f.PrimaryColor).HasMaxLength(7).IsFixedLength();
    }
}
