using IplStore.Domain.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IplStore.Infrastructure.Persistence.Configurations;

// Column names come from UseSnakeCaseNamingConvention() (StockQuantity -> stock_quantity).
// Only table names, types and relationships are configured explicitly here.
// Keys are generated by the application => ValueGeneratedNever (also stops EF from treating
// a new child with a pre-set key as "existing" and issuing an UPDATE instead of an INSERT).

internal sealed class ProductCategoryConfiguration : IEntityTypeConfiguration<ProductCategory>
{
    public void Configure(EntityTypeBuilder<ProductCategory> builder)
    {
        builder.ToTable("product_categories");
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).ValueGeneratedNever();
        builder.Property(c => c.Code).HasMaxLength(40);
        builder.Property(c => c.Name).HasMaxLength(80);
    }
}
