using IplStore.Domain.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IplStore.Infrastructure.Persistence.Configurations;

// Column names come from UseSnakeCaseNamingConvention() (StockQuantity -> stock_quantity).
// Only table names, types and relationships are configured explicitly here.
// Keys are generated by the application => ValueGeneratedNever (also stops EF from treating
// a new child with a pre-set key as "existing" and issuing an UPDATE instead of an INSERT).

internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("products");
        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id).ValueGeneratedNever();
        builder.Property(p => p.Sku).HasMaxLength(40);
        builder.Property(p => p.Name).HasMaxLength(200);
        builder.Property(p => p.Price).HasPrecision(12, 2);
        builder.Property(p => p.Currency).HasMaxLength(3).IsFixedLength();
        builder.Property(p => p.ImageUrl).HasMaxLength(500);

        // PostgreSQL system column xmin changes on every row update -> free optimistic
        // concurrency token without an extra column.
        builder.Property(p => p.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        builder.HasOne(p => p.Franchise).WithMany().HasForeignKey(p => p.FranchiseId);
        builder.HasOne(p => p.Category).WithMany().HasForeignKey(p => p.CategoryId);
    }
}
