-- =============================================================================
-- V001 - Normalised WRITE model (3NF) - source of truth for all commands.
--
-- Conventions
--   * snake_case identifiers, plural table names
--   * UUID primary keys generated by the application (no hot-spot sequences,
--     safe to generate on any node -> friendly to sharding / multi-writer)
--   * timestamptz everywhere (UTC on the wire)
--   * money = numeric(12,2) + ISO-4217 currency code
--   * every business invariant that MUST hold under concurrency is enforced
--     by a constraint here, not only in code (defence in depth)
--
-- Migrations are immutable once applied: the runner stores a checksum and
-- refuses to start if an applied script is edited. Add a new V00X file instead.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- trigram indexes for partial-text search

-- ---------------------------------------------------------------- reference data
CREATE TABLE franchises (
    id              uuid         PRIMARY KEY,
    code            varchar(8)   NOT NULL,
    name            varchar(100) NOT NULL,
    city            varchar(60)  NOT NULL,
    primary_color   char(7)      NOT NULL DEFAULT '#1f2937',   -- UI accent (#RRGGBB)
    created_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_franchises_code UNIQUE (code),
    CONSTRAINT ck_franchises_color CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$')
);

-- Categories are data, not an enum: adding "Mug" is an INSERT, not a deploy.
CREATE TABLE product_categories (
    id              uuid         PRIMARY KEY,
    code            varchar(40)  NOT NULL,
    name            varchar(80)  NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_categories_code UNIQUE (code)
);

-- ---------------------------------------------------------------- catalogue
CREATE TABLE products (
    id              uuid          PRIMARY KEY,
    sku             varchar(40)   NOT NULL,
    name            varchar(200)  NOT NULL,
    description     text          NOT NULL DEFAULT '',
    franchise_id    uuid          NOT NULL REFERENCES franchises(id),
    category_id     uuid          NOT NULL REFERENCES product_categories(id),
    price           numeric(12,2) NOT NULL,
    currency        char(3)       NOT NULL DEFAULT 'INR',
    stock_quantity  integer       NOT NULL,
    image_url       varchar(500),
    attributes      jsonb         NOT NULL DEFAULT '{}'::jsonb,  -- sizes, material, signed_by ...
    is_active       boolean       NOT NULL DEFAULT true,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    updated_at      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    -- Last line of defence against overselling: even a buggy writer cannot
    -- push stock below zero.
    CONSTRAINT ck_products_stock_non_negative CHECK (stock_quantity >= 0)
);
CREATE INDEX ix_products_franchise ON products (franchise_id);
CREATE INDEX ix_products_category  ON products (category_id);

-- ---------------------------------------------------------------- customers
CREATE TABLE customers (
    id              uuid         PRIMARY KEY,
    email           varchar(254) NOT NULL,
    full_name       varchar(150) NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now()
);
-- Case-insensitive uniqueness: "A@x.com" and "a@x.com" are the same customer.
CREATE UNIQUE INDEX uq_customers_email ON customers (lower(email));

-- ---------------------------------------------------------------- cart
CREATE TABLE carts (
    id              uuid         PRIMARY KEY,
    customer_id     uuid         NOT NULL REFERENCES customers(id),
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    -- Exactly ONE active cart per customer. Concurrent "get-or-create" calls
    -- use INSERT .. ON CONFLICT DO NOTHING against this constraint.
    CONSTRAINT uq_carts_customer UNIQUE (customer_id)
);

CREATE TABLE cart_items (
    id              uuid         PRIMARY KEY,
    cart_id         uuid         NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    customer_id     uuid         NOT NULL,          -- denormalised distribution key (see docs/06)
    product_id      uuid         NOT NULL REFERENCES products(id),
    quantity        integer      NOT NULL,
    added_at        timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0),
    -- No duplicate lines: adding the same product again increments quantity.
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id)
);
CREATE INDEX ix_cart_items_customer ON cart_items (customer_id);

-- ---------------------------------------------------------------- orders
CREATE TABLE orders (
    id                uuid          PRIMARY KEY,
    order_number      varchar(32)   NOT NULL,
    customer_id       uuid          NOT NULL REFERENCES customers(id),
    idempotency_key   varchar(100)  NOT NULL,
    status            varchar(20)   NOT NULL,
    currency          char(3)       NOT NULL,
    subtotal          numeric(12,2) NOT NULL,
    tax               numeric(12,2) NOT NULL,
    shipping          numeric(12,2) NOT NULL,
    total             numeric(12,2) NOT NULL,
    item_count        integer       NOT NULL,       -- denormalised: list page needs no join
    customer_name     varchar(150)  NOT NULL,       -- snapshot at time of purchase
    customer_email    varchar(254)  NOT NULL,       -- snapshot at time of purchase
    placed_at         timestamptz   NOT NULL,
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    -- Idempotency: a retried / double-clicked checkout can never create a
    -- second order for the same (customer, key).
    CONSTRAINT uq_orders_customer_idempotency UNIQUE (customer_id, idempotency_key),
    CONSTRAINT ck_orders_status CHECK (status IN ('Placed','Paid','Shipped','Delivered','Cancelled')),
    CONSTRAINT ck_orders_total CHECK (total = subtotal + tax + shipping),
    CONSTRAINT ck_orders_item_count CHECK (item_count > 0)
);
-- Order history = "my orders, newest first" -> covering composite index.
CREATE INDEX ix_orders_customer_placed ON orders (customer_id, placed_at DESC);

-- Denormalised line snapshot: order history must show what the customer
-- actually bought, even if the product is renamed, repriced or deleted later.
CREATE TABLE order_items (
    id              uuid          PRIMARY KEY,
    order_id        uuid          NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    customer_id     uuid          NOT NULL,         -- denormalised distribution key (see docs/06)
    product_id      uuid          NOT NULL,         -- intentionally NO FK: history outlives catalogue
    sku             varchar(40)   NOT NULL,
    product_name    varchar(200)  NOT NULL,
    franchise_name  varchar(100)  NOT NULL,
    category_name   varchar(80)   NOT NULL,
    unit_price      numeric(12,2) NOT NULL,
    quantity        integer       NOT NULL,
    line_total      numeric(12,2) NOT NULL,
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_line_total CHECK (line_total = unit_price * quantity),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id)
);
CREATE INDEX ix_order_items_order ON order_items (order_id);
